spring.application.name=fgback
spring.datasource.url=jdbc:sqlserver://ccv-server.database.windows.net:1433;databaseName=db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username=ccv
spring.datasource.password= song0917!!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
runtimeOnly='io.jsonwebtoken:jjwt-impl:0.11.5'
jwt.secret=ThisIsASecretKeyForJwtGenerationAndItMustBeLongEnough
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.enabled=true

spring.servlet.encoding.force=true

spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql=true
debug=true
